#!/bin/bash
set -euo pipefail

# =============================================================================
# agent-open-pr.sh
# 표준화된 PR 생성 스크립트
# 사용법: bash scripts/agent-open-pr.sh "PR 제목" [exec-plan-file]
# 전제조건: scripts/agent-validate.sh 통과 후 실행
# =============================================================================

PR_TITLE="${1:-}"
EXEC_PLAN_FILE="${2:-}"

if [ -z "$PR_TITLE" ]; then
  echo "Usage: bash scripts/agent-open-pr.sh \"PR 제목\" [exec-plan-file]"
  echo "Example: bash scripts/agent-open-pr.sh \"feat: add todo avoidance scoring\""
  exit 1
fi

# 제목 형식 검증 (Conventional Commits)
if ! echo "$PR_TITLE" | grep -qE "^(feat|fix|chore|docs|refactor|test|perf|ci|build|revert): .+"; then
  echo "ERROR: PR title must follow conventional commits format"
  echo "  Valid prefixes: feat|fix|chore|docs|refactor|test|perf|ci|build|revert"
  exit 1
fi

# main 브랜치 직접 push 방지
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" = "main" ]; then
  echo "ERROR: Cannot create PR from main branch. Create a feature branch first."
  exit 1
fi

# PR 크기 확인
CHANGED_FILES=$(git diff --name-only main...HEAD 2>/dev/null | wc -l | tr -d ' ')
DIFF_LINES=$(git diff main...HEAD --stat 2>/dev/null | tail -1 | grep -oE '[0-9]+ insertion' | grep -oE '[0-9]+' || echo "0")

SIZE_WARNINGS=""
if [ "$CHANGED_FILES" -gt 10 ]; then
  SIZE_WARNINGS="${SIZE_WARNINGS}\n⚠️ Large PR: ${CHANGED_FILES} files (recommended ≤10)"
fi
if [ "$DIFF_LINES" -gt 400 ]; then
  SIZE_WARNINGS="${SIZE_WARNINGS}\n⚠️ Large diff: ${DIFF_LINES} lines (recommended ≤400)"
fi

# exec-plan 정보 추출
PLAN_SUMMARY="N/A"
if [ -n "$EXEC_PLAN_FILE" ] && [ -f "$EXEC_PLAN_FILE" ]; then
  PLAN_ID=$(grep "^id:" "$EXEC_PLAN_FILE" 2>/dev/null | sed 's/id: //' || echo "")
  PLAN_ISSUE=$(grep "^issue:" "$EXEC_PLAN_FILE" 2>/dev/null | sed 's/issue: //' || echo "")
  PLAN_SUMMARY="[$PLAN_ID]($EXEC_PLAN_FILE)"
  [ -n "$PLAN_ISSUE" ] && PLAN_SUMMARY="${PLAN_SUMMARY} — Closes ${PLAN_ISSUE}"
fi

# 변경 파일 목록 (최대 20개)
CHANGED_FILES_LIST=$(git diff --name-only main...HEAD 2>/dev/null | head -20 | sed 's/^/- /' || echo "- (없음)")

# Draft PR 생성
gh pr create \
  --title "$PR_TITLE" \
  --draft \
  --body "$(cat <<EOF
## Summary
<!-- 변경 내용을 3줄 이내로 설명 -->

## Changes
${CHANGED_FILES_LIST}

## Validation
- [x] \`scripts/agent-validate.sh\` passed
- [x] Tests added/updated
- [x] Docs updated (if applicable)
- [ ] Human review (if required)

## Exec Plan
${PLAN_SUMMARY}

---
🤖 Generated by Claude Code Agent | See AGENTS.md
EOF
)"

echo ""
echo "✓ Draft PR created from branch: ${CURRENT_BRANCH}"
echo "  Review and mark ready when complete."
